import { perks } from './perks';
import balance from '../engine/balance.json';
import { enemyNames, enemyUrls, workshop, powerUrls } from './assets';
import { weapons as weaponNames, powers } from '../scripts/playtest-policy.mjs';
export { weaponNames };
const weaponDescriptions=['Unlimited fire; shares upgrades with Light Speed.','Instant hit; one fewer standard hit to kill.','Homing rockets; starts at two shots per second.','Homing bomb with six unguided splits.'];
const enemyDescriptions=['Approaches the tower.','Fast and fragile.','Heavy; resists knockback.','Shoots from your range line.','Shields nearby enemies from passive damage.','Immune to control.','Drains health at range.','Spins up a powerful shot.','Splits into three smaller Scatters.','Buffs nearby enemies.','Disables a weapon or combat stat.','Bouncing shot doubles damage each hit.','Every tenth wave; slow, durable, resists instant kills.'];
const descriptions=['Chains hits between enemies.','Slows enemies just beyond range.','Brief stun; 1 damage every 4s.','Two traps; pulls inward and deals one bullet hit per second.','Three beams amplify damage and coins.','Clears Basics, Fasts and Ranged; extra hits to others. Fires 3s, rests 2s.','Multiplies kill coins.','Heals into Overheal capacity.','Bank three screen clears; bosses take fixed damage.','Blocks one hit; stacks to three.','Clears Basics, Fasts and Ranged; halves enemy attack speed for 30s.','10s invincibility; double damage for 30s. Repeat pickups extend damage only.','5% of enemies die in one hit.','Moves permanent mines into an evenly spaced inner orbit.','Hits can reduce enemy speed and mass.','Activates or extends GT, SL and BH together.','Three faster, stronger Orbs through Black Hole centers.','Doubles splash size and damage; Chrono reach gains only 15%.','Aura boosts coin and Stone income; does not attack.','Aura doubles damage from other sources; does not attack.','Pulses every 5s; increasing burn hits over 5s.','Contact stuns for 3s, then slows for 5s.','Lets Basics drop coins.'];
const section=(title:string,body:string,open=false)=>`<details class="help-section"${open?' open':''}><summary>${title}</summary>${body}</details>`;
const group=(title:string,indices:number[])=>`<h3>${title}</h3><dl class="help-powers">${indices.map(i=>`<dt><img src="${powerUrls[i]}" width="24" height="24" alt="">${powers[i]}</dt><dd>${descriptions[i]}</dd>`).join('')}</dl>`;
export function renderHelp({live,best,time,seed}:{live:boolean;best:number;time:string;seed:number}):string {
 return `<div class="modal-top"><h2 id="modal-title">How To Play</h2></div><div class="help-body">
 ${section('Controls',`<dl class="help-controls"><dt>Mouse</dt><dd>Aim and hold to fire.</dd><dt>Touch</dt><dd>Drag the trackpad to aim; hold Fire. Lift to reposition.</dd><dt>Switch Weapon</dt><dd><kbd>1–4</kbd> or mouse wheel.</dd><dt>Death Wave</dt><dd><kbd>Q</kbd> or right click.</dd><dt>Pause</dt><dd><kbd>Esc</kbd>.</dd><dt>Keyboard Aim</dt><dd>Arrow keys; Space fires.</dd></dl><p>Hook Bomb fires once per press.</p>`,true)}
 ${section('Weapons & Survival',`<div class="help-weapons">${weaponNames.map((name,i)=>`<div><kbd>${i+1}</kbd><strong>${name}</strong><span>${weaponDescriptions[i]}</span></div>`).join('')}</div><ul><li>Outside range: half damage; bosses take a quarter. Bombs cannot instantly kill outside range.</li><li>Contact attacks once per second. Thorns retaliates; half effect against bosses.</li><li>Wall blocks contact, then rebuilds when broken. Ranged attacks bypass it.</li><li>Shields block individual hits, not Vampire drain.</li><li>Proc meters are steady: 10% triggers every ten eligible actions.</li></ul>`)}
 ${section('Pickups & Powers',`<p>Shoot powers to activate them. Coins and ammo collect automatically. Timed pickups add remaining time up to your Power Stack Cap (50–70s). Demon invincibility never stacks or exceeds 10s.</p>${group('Damage & Control',[0,1,2,3,4,5,8,16,17])}${group('Survival & Economy',[6,7,9,10,11,22])}${group('Modules',[12,13,14,15])}${group('Bots',[18,19,20,21])}`)}
 ${section('Ammo & Income',`<ul><li>Direct weapon kills supply ammo; all kills can drop powers.</li><li>Ammo pickups: +35 Light Speed, +2 Missiles; every fourth adds +1 Hook Bomb. Ammo Quantity adds 20% per level; capacity limits reserves.</li><li>Every ${balance.precision_ammo.hits} original manual cannon hits refill ${balance.precision_ammo.light} Light Speed and ${balance.precision_ammo.missiles} Missile; every ${balance.precision_ammo.hook_every} refills add ${balance.precision_ammo.hooks} Hook Bomb. Extras, bounces and automatic shots do not count.</li><li>Basics need Critical Coin to earn coins. Coins/Kill multiplies income.</li><li>GT, BH, SL, Orb kills and DW marks each add 15% coins, multiplying together. Gold Bot adds its own bonus.</li><li>Special enemies give Stones: 1 each, bosses 2, Super Bosses 5.</li></ul>`)}
 ${section('Workshop & Power Shop',`<p>Coins buy run upgrades and Supplies. Stones buy power effects and Drop Share; Drop Share changes the mix, not total drops. Hold an upgrade to buy repeatedly.</p><details class="help-reference"><summary>Workshop Stat Reference</summary><dl class="upgrade-help">${workshop.map(({index,label})=>`<dt>${label}</dt><dd>${balance.upgrades[index].description}</dd>`).join('')}</dl></details>`)}
 ${section('Autocannon & Automation',`<ul><li>Autocannon fires alongside your manual weapon. Target Priority ranks enemies and powers; higher rules win.</li><li>Efficiency raises its stats from 10% to 110%. Targeting Speed improves movement; Auto Weapons unlocks special weapons. Ammo is shared.</li><li>Buy purchases once. Its checkbox repeats between waves and starts the next wave after 5s; uncheck to stop.</li><li>Buy & Perk Priorities sets purchase order, level limits and perk choices.</li><li>Auto Play is separate, with adjustable reaction, aim and switch speed. It spends its starting budget before combat and runs out of focus.</li></ul>`)}
 ${section('Perks',`<p>Choose one of three after waves 5, 15, 30, 50, 75, then increasingly spaced waves. The HUD shows the next choice; Your Perks lists your build. Tradeoffs apply both bonuses and penalties.</p><dl class="upgrade-help">${perks.map(({name,effect,cap})=>`<dt>${name} · ${cap} ${cap===1?'Level':'Levels'}</dt><dd>${effect}</dd>`).join('')}</dl>`)}
 ${section('Enemies',`<div class="enemy-list">${enemyNames.map((name,i)=>`<div><img src="${enemyUrls[i]}" width="28" height="28" alt=""><strong>${name}</strong><span>${balance.enemies[i].hp} Base HP</span><small>${enemyDescriptions[i]}${balance.enemies[i].weapon_damage.some(m=>m!==1)?' · '+balance.enemies[i].weapon_damage.map((m,w)=>m===1?'':`${weaponNames[w]} ${m}×`).filter(Boolean).join(', '):''}</small></div>`).join('')}</div><p>Every tenth wave adds one cannon hit of health. Wave 400 maps to Tower wave 10,000 for movement and special arrivals. Protectors block passive damage; direct weapons and Death Wave still work.</p>`)}
 ${section('Waves, Reports & Fresh Starts',`<ul><li>Spawning lasts 30s, then cleanup. Start the next wave when ready.</li><li>Accuracy counts main shots hitting enemies or powers; excludes extras, bounces and splits.</li><li>Hits Taken excludes shields and Vampire drain. Earned coins exclude starting budgets.</li><li>Three retries replay your last cleared tenth-wave checkpoint.</li><li>Fifty-wave milestones unlock fresh starts with empty shops and a budget. Fresh starts at wave 50+ get 20s of Chrono Field, Black Hole, Spotlight, Golden Tower, Extra Orbs and Critical Coin, plus one Shield. Shopping does not consume this kit.</li><li>Clear each 30 waves to unlock skins; backgrounds change too.</li></ul><p>Best: ${best} waves · This Run: ${time} · Seed ${seed}<br>Music: Krisu · The Tower soundtrack.</p>`)}
 </div><div class="modal-actions"><button class="primary" id="close-help">${live?'Back To Game':'Close'}</button></div>`;
}
